[package]
name = "rllmjson"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
publish = false

[lib]
crate-type = ["staticlib"]
name = "llmjson"

[dependencies]
extendr-api = "0.8.1"
llm_json = "1.0"
serde_json = "1.0"
indexmap = "2.0"
